### ISSUE TITLE
Some weird errors

### ISSUE THREAD

**Issue by takaqiao** [TeamUlysses/ulib#57] opened 2019-07-17 02:31 UTC
### Steps to reproduce
1.Seems like it will show up when player completely join the server(after connecting)

### Expected behavior
No idea

### Actual behavior
No idea

### Error(s) in server console, if any
[ERROR] lua/includes/modules/hook.lua:120: attempt to index local 'gm' (a number
 value)
  1. Call - lua/includes/modules/hook.lua:120
   2. fn - addons/ulib/lua/ulib/cl_init.lua:58
    3. func - addons/ulib/lua/ulib/client/cl_util.lua:22
     4. unknown - lua/includes/extensions/net.lua:32

### Version
ULib v2.63
ULX v3.73

**Comment by bigdogmat** [comment] 2019-07-17 03:23
It seems like `_` is a number value and `hook.Call` is attempting to index it cause that's the gamemode argument.
https://github.com/TeamUlysses/ulib/blob/e887b4086124a69fad9efd58ce6ce4311d60e3aa/lua/ulib/cl_init.lua#L58

ulib has built in protection against `_` being changed though it only works if it's able to change the meta table of the `_G` table.
https://github.com/TeamUlysses/ulib/blob/c44d23fd82e394982eb361516140757f2fabcc54/lua/ulib/shared/misc.lua#L1014

ulib shouldn't rely on `_` being nil as that's a really easy way for stupid bugs like this to occur. What's even the reason for using `_` instead of nil?

**Comment by takaqiao** [comment] 2019-07-17 16:07
> It seems like `_` is a number value and `hook.Call` is attempting to index it cause that's the gamemode argument.
> https://github.com/TeamUlysses/ulib/blob/e887b4086124a69fad9efd58ce6ce4311d60e3aa/lua/ulib/cl_init.lua#L58
> 
> ulib has built in protection against `_` being changed though it only works if it's able to change the meta table of the `_G` table.
> https://github.com/TeamUlysses/ulib/blob/c44d23fd82e394982eb361516140757f2fabcc54/lua/ulib/shared/misc.lua#L1014
> 
> ulib shouldn't rely on `_` being nil as that's a really easy way for stupid bugs like this to occur. What's even the reason for using `_` instead of nil?

I see.. U have any temp fix for this?

**Comment by bigdogmat** [comment] 2019-07-17 19:17
temp temp fix, `lua_run _ = nil`
temp fix, change that line and every other that uses `_` as an argument expecting it to be nil, to nil

Or you could try to figure out why the meta table protection didn't work, my only guess would be another addon overwriting it.

**Comment by ghost** [comment] 2020-06-09 16:16
> temp temp fix, `lua_run _ = nil`
> temp fix, change that line and every other that uses `_` as an argument expecting it to be nil, to nil
> 
> Or you could try to figure out why the meta table protection didn't work, my only guess would be another addon overwriting it.

Sorry to bring up an old post, but I'm receiving this exact same lua error too. The temp fix you put, where would I do this? As in the `lua_run _ = nil`. Sorry, I know very little about lua.

**Comment by bigdogmat** [comment] 2020-06-12 02:21
It's a console command, depending on the realm you're getting the error from you run it either in server console or client console.

**Comment by ghost** [comment] 2020-06-12 07:52
> It's a console command, depending on the realm you're getting the error from you run it either in server console or client console.

How would you go about a more permanent fix?

**Comment by bigdogmat** [comment] 2020-06-12 09:45
I listed 2 in my previous comment

**Comment by ghost** [comment] 2020-06-12 10:15
Sorry, I don't know lua.
Can you explain it in idiot terms for me? haha

**Comment by zpetty33** [comment] 2022-08-05 23:19
Unable to reproduce. Closing ticket. If you find a way to reliably reproduce the error, please let us know.

**Closed as completed by zpetty33** 2022-08-05 23:19 UTC
